TravelProject/urls.py
from django.contrib import admin
from django.urls import path
from Vtur import views as VturViews

from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', VturViews.home, name='home'),
    path('orders/', VturViews.orders, name='orders'),
    path('register/', VturViews.register, name='register'),
    path('<str:tour_type>/<int:tour_id>/', VturViews.tour_detail, name='tour_detail'),
    path('<str:tour_type>/', VturViews.tour_list, name='tour_list'),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

Vtur/models.py
from django.db import models
from django.conf import settings




from django.contrib.auth.models import User

class Tour(models.Model):

    TOUR_TYPES = [('i', "Island"), ('g', "Georgia"), ('s', "Swamp"), ('f', "Float")]

    title = models.CharField(max_length=100, blank=False)
    tour_type = models.CharField(blank=False, max_length=1, choices=TOUR_TYPES)
    description = models.TextField(blank=False)
    program = models.TextField(blank=False)
    cost = models.IntegerField(blank=False)
    start_date = models.DateField(blank=False)
    end_date = models.DateField(blank=False)
    vacant_spot = models.IntegerField()
    image = models.ImageField(upload_to="uploads")


    def __str__(self):
        return f"{self.title} {self.start_date} - {self.end_date}"


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    tour = models.ForeignKey('Tour', on_delete=models.CASCADE)
    person_numbers = models.IntegerField(default=1)
    contact_phone = models.CharField(blank=False, max_length=13)


    def __str__(self):
        return f" order #{self.id}"

Vtur/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class AddOrder(forms.Form):
    person_numbers = forms.IntegerField(min_value=1, label='Количество человек')
    contact_phone = forms.RegexField(regex=r'^\+375\d{9}$', label='Номер телефона', error_messages={'invalid':'Введите телефон в формате +375ххххххххх'})

class UserRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat password', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords don\'t match.')
        return cd['password2']

Vtur/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Tour, Order
from django.contrib.auth import get_user
from .forms import AddOrder, UserRegistrationForm
from django.contrib import messages


def near_tours():
    near_tours = Tour.objects.all().order_by('start_date')[:3]
    return near_tours

def home(request):
    return render(request, 'home.html',{'near_tours':near_tours()})

def tour_list(request, tour_type):
    tours = []
    unique_tours = set(Tour.objects.filter(tour_type=tour_type).values_list('title', flat=True))
    for title in unique_tours:
        tours += [Tour.objects.filter(title=title)[0]]
    return render(request, 'tour_list.html', {'tours': tours,'near_tours':near_tours()})


def tour_detail(request, tour_id, tour_type):
    tour = get_object_or_404(Tour, id=tour_id)
    tours = Tour.objects.filter(title=tour.title).order_by('start_date')
    if request.method == "POST":

        form = AddOrder(request.POST)

        if form.is_valid():
            order = Order()
            order.person_numbers = form.cleaned_data['person_numbers']
            order.contact_phone = form.cleaned_data['contact_phone']
            order.user = get_user(request)
            tour = get_object_or_404(Tour, start_date=request.POST['start_date'])
            order.tour = tour


            if int(order.person_numbers) <= tour.vacant_spot:
                tour.vacant_spot = tour.vacant_spot - int(order.person_numbers)
                tour.save()
                order.save()
                return render(request, 'tour_confirm.html', {'tour': order.tour})
            else:
                messages.add_message(request, messages.INFO, 'Недостаточно свободных мест')
                redirect('tour_confirm.html', {'tour_id':tour_id})
    else:
        form = AddOrder()

    return render(request, 'tour_detail.html', {'tour':tour, 'tours':tours,'near_tours':near_tours(), 'form':form})


def register(request):
    if request.method == 'POST':
        user_form = UserRegistrationForm(request.POST)
        if user_form.is_valid():
            new_user = user_form.save(commit=False)
            new_user.set_password(user_form.cleaned_data['password'])
            new_user.save()
            return render(request, 'register_done.html', {'new_user': new_user})
    else:
        user_form = UserRegistrationForm()
    return render(request, 'register.html', {'user_form': user_form})

def orders(request):
    orders = Order.objects.all().order_by('-id')
    return render(request, 'order_list.html', {'orders': orders})

Vtur/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vtur</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'Vtur/css/style.css' %}">
</head>
<body>
<div>
    <div class="header">
        <a href="{% url 'home' %}">
            <h1 style="font-size: 90px">ВЖУХ-ТУР</h1>
        </a>

    </div>
    <div class="row" style="padding-left: 15px">
        <div class="col-2">
            {% block near_starts %}
            {% endblock near_starts %}
        </div>
        <div class="col-8">

            {% block content %}
            {% endblock %}
        </div>
        <div class="col">
            <ul>
                {% if user.is_authenticated %}
                    <li>User: {{ user.get_username }}</li>
                    <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
                {% endif %}

            </ul>
            <div>
                {% if perms.Vtur.delete_order %}

                    <button type="button" class="btn btn-outline-primary"><a href="{% url 'orders' %}"
                                                                             style="text-align: right">Посмотреть
                        заказы</a></button>
                {% endif %}
            </div>
        </div>

        <div class="footer">
            <div class="row">
                <div class="col-8">
                <pre style="font-size: medium">
                    Контакты:

                    тел: +375 22 112 3535
                         +375 11 212 1122
                </pre>
                </div>
                <div class="col-4" style="text-align: left">
                    <p>  Мы в соцсетях:</p>
                    <p><a href="https://www.facebook.com/dubinin.travel/">
                    <img src="{% static 'Vtur/img/fb.svg' %}" target="_blank"> dubinin.travel</a></p>
                    <p><a href="https://www.instagram.com/andrey_dubinin/?hl=ru" target="_blank">
                        <img src="{% static 'Vtur/img/inst.svg' %}">andrey_dubinin</a> </p>
                    <p><a href="https://t.me/dubinintour" target="_blank">
                        <img src="{% static 'Vtur/img/tgm.svg' %}">dubinintour</a></p>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
</html>

Vtur/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block near_starts %}

    <h3 class="underline">Ближайшие старты:</h3>
    {% for near_tour in near_tours %}
        <a href="{% url 'tour_detail'  near_tour.tour_type near_tour.id %}">
            <img width="90px" height="70px" src="{{ near_tour.image.url }}">
            <p>{{ near_tour.start_date|date:"d.m.Y" }} {{ near_tour.title }}</p>
        </a>
    {% endfor %}


{% endblock near_starts %}
{% block content %}


    <div class="row">

        <div class="col">
            <a href="{% url 'tour_list' tour_type='i' %}">
                <h1>Исландия</h1>
                <img src="{% static 'Vtur/img/Island.jpg' %}" width="100%" , height="70%"></a></div>
        <div class="col">
            <a href="{% url 'tour_list' tour_type='g' %}">
                <h1>Грузия</h1>
                <img src="{% static 'Vtur/img/Georgia.jpg' %}" width="100%" , height="70%"></a>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <a href="{% url 'tour_list' tour_type='s' %}">
                <h1>Болота</h1>
                <img src="{% static 'Vtur/img/Swamp.jpg' %}" width="100%" , height="70%"></a>
        </div>
        <div class="col">
            <a href="{% url 'tour_list' tour_type='f' %}">
                <h1>Сплавы на плотах</h1>
                <img src="{% static 'Vtur/img/Float.jpg' %}" width="100%" , height="70%"></a>
        </div>
    </div>
{% endblock %}

Vtur/templates/order_list.html
{% extends 'base.html' %}


{% block content %}
    {% for order in orders %}
        <div style="padding-bottom: 20px">
            <p> <span class="bold">Пользователь: </span> {{ order.user.username }}</p>
        <p> <span class="bold">Тур: </span>{{ order.tour.title }}</p>
        <p> <span class="bold">Даты: </span>{{ order.tour.start_date|date:"d.m.Y" }} - {{ order.tour.end_date|date:"d.m.Y" }}</p>
        <p> <span class="bold">Количество человек: </span>{{ order.person_numbers }}</p>
        <p> <span class="bold">Номер телефона: </span>{{ order.contact_phone }}</p>

        </div><hr>
    {% endfor %}
{% endblock %}

Vtur/templates/register.html
{% extends "base.html" %}

{% block content %}
    <h1>Регистрация нового пользователя</h1>
    <p>Пожалуйста, заполните форму:</p>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <table>
            {{ user_form }}
        </table>
        <p><input type="submit" value="Создать учетную запись"></p>
    </form>
{% endblock %}

Vtur/templates/register_done.html
{% extends "base.html" %}


{% block content %}
    <h1>Добро пожаловать, {{ new_user.first_name }}!</h1>
    <p>Учетная запись создана. Теперь вы можете <a href="{% url "login" %}"><span class="underline"> войти в систему</span></a>.</p>
{% endblock %}

Vtur/templates/tour_confirm.html
{% extends 'base.html' %}

{% block content %}
    <div class="tour">
        <h6> Вы успешно забронировали тур</h6>
        <h1>{{ tour.title }}</h1>
        <br>
        <br>
        <br>
        <a href="{% url 'home' %}">
            <p>Вернуться на главную страницу</p>
        </a>
    </div>

{% endblock %}

Vtur/templates/tour_detail.html
{% extends 'base.html' %}6

{% block content %}
    <div style="padding-bottom: 20px ">
        <h1>{{ tour.title }}</h1>
    <br>
        <h4 class="underline">Программа тура</h4>
        <p>{{ tour.program|linebreaksbr }}
        <hr>
            {% for t in tours %}
                {% if t.vacant_spot > 0 %}
                    <p><span class="bold">Даты:   </span>{{ t.start_date|date:"d.m.Y" }} - {{ t.end_date|date:"d.m.Y" }}</p>
                    <p><span class="bold">Количество свободных мест: </span>{{ t.vacant_spot }} </p>
                    <p><span class="bold">Стоимость:</span> {{ t.cost }} $</p>

                    <div>
                        {% if messages %}
                            <ul class="messages">
                                {% for message in messages %}
                                    <li{% if message.tags %} class="{{ message.info }}"{% endif %}>{{ message }}</li>
                                {% endfor %}
                            </ul>
                        {% endif %}


                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            <table>
                                {{ form }}
                                <input value="{{ t.start_date|date:"Y-m-d" }}" name="start_date" hidden>
                            </table>
                            {% if user.is_authenticated %}
                                <button type="submit" class="btn btn-outline-primary">Забронировать</button>
                            {% else %}
                                <a href="{% url 'login' %}?next={{ request.path }}">Войдите на сайт, чтобы забронировать
                                    тур </a>
                            {% endif %}
                        </form>
                    </div>
                    <hr>
                {% endif %}
            {% endfor %}
    </div>

{% endblock %}

Vtur/templates/tour_list.html
{% extends 'base.html' %}
{% block near_starts %}

    <h3 class="underline">Ближайшие старты:</h3>
    {% for near_tour in near_tours %}
        <a href="{% url 'tour_detail'  near_tour.tour_type near_tour.id %}">
            <img width="30%" src="{{ near_tour.image.url }}">
            <p>{{ near_tour.start_date|date:"d.m.Y" }} {{ near_tour.title }}</p>
        </a>
    {% endfor %}


{% endblock near_starts %}
{% block content %}
    {% for tour in tours %}
        <h1>{{ tour.title }}</h1>
        <div style="display:flex; padding-bottom: 30px">
            <a href="{% url 'tour_detail' tour.tour_type tour.id %}">

                    <img width="300px" hight="300px " src="{{ tour.image.url }}"style="padding-right: 20px" >
            </a>
        {{ tour.description }}
        </div>
    {% endfor %}
{% endblock %}